### ISSUE TITLE
"Get service 'ds_agent' status" task raises Ansible warning

### ISSUE THREAD

**Issue by aodj** [deep-security/ansible#7]
When installing on a Linux OS, the `"Get service 'ds_agent' status"` [task](https://github.com/deep-security/ansible/blob/ec44e13a8061ceef5160d1c808c6759b3e3c49ab/tasks/install-linux.yml#L129-L132) causes Ansible to raise a warning:

```bash
TASK [deep-security.deep-security-agent : Get service 'ds_agent' status] ****
 [WARNING]: Consider using service module rather than running service
```

Relevant links:
[1]: http://docs.ansible.com/ansible/latest/service_module.html
[2]: https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/modules/commands/command.py#L99-L115

**Comment by DeepSecurityOpenSourceSupport** [comment]
Thanks @aodj ,

We'll follow this up.

Best Regards,
Deep Security Open Source Support team

**Comment by DeepSecurityOpenSourceSupport** [comment]
This issue is solved in https://github.com/deep-security/ansible/pull/8
As the service module does not have status check function yet:
https://github.com/ansible/ansible/issues/30172 For Service module not support status checking
Once the change is merged, we'll consider to refactor this again
https://github.com/ansible/ansible/pull/20177  For adding status into Service module

For now, we hide the service warning to avoid confusing.
